version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${ServerPort}:${ServerPort}
      - ${DebugPort}:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: web
    