version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${ServerPort}:${ServerPort}
      - ${DebugPort}:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: web
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    container_name: mongo-db
    
    ports:  
     - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
